package com.isliam.techshop.service.sell;

import org.flowable.engine.delegate.DelegateExecution;
import org.flowable.engine.delegate.JavaDelegate;

public class SuccessfulPurchaseDelegate implements JavaDelegate {

	@Override
	public void execute(DelegateExecution execution) {

	    System.out.println("SUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSS" +
            "SUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSS" +
            "SUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSS" +
            "SUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSS" +
            "SUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSS" +
            "SUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSS" +
            "SUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSSSUCCCEEESSS");
		// TODO Auto-generated method stub

	}

}
